// erp-new/client-vue/src/views/SalesShipmentPage.vue
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue';
import { ElMessage } from 'element-plus';
import ErpBillPage from '@/components/erp/ErpBillPage.vue';
import ErpBillToolbar from '@/components/erp/ErpBillToolbar.vue';
import ErpBillQueryField from '@/components/erp/ErpBillQueryField.vue';
import ErpBillLineTable from '@/components/erp/ErpBillLineTable.vue';
import ErpBillHeadExtFields from '@/components/erp/ErpBillHeadExtFields.vue';
import ErpBillAuditMeta from '@/components/erp/ErpBillAuditMeta.vue';
import { INV_CA, pickQuery, pickList, pickForm } from '@/config/fields';
import LookupDialog from '@/components/LookupDialog.vue';
import LookupField from '@/components/LookupField.vue';
import LookupPicker from '@/components/LookupPicker.vue';
import { getLookupDialogProps, getInlineLookupDialogProps } from '@/config/lookups';
import BilSpcSalesLookupDialog from '@/components/BilSpcSalesLookupDialog.vue';
import { api } from '@/api';
import { useBillLineAddRows } from '@/composables/useBillLineAddRows';
import { resolveLineProductByCode } from '@/utils/billLineProductLookup';
import type {
  BilSpc,
  Cust,
  Dept,
  OpenSalesOrder,
  Product,
  SalesShipmentHead,
  SalesShipmentLine,
  Salm,
  Warehouse,
} from '@/api/types';
import { calcLineAmounts, sumLines } from '@/utils/tax';
import { buildBillSavePayload } from '@/utils/billExtPayload';
import { useErpBillEditDelete } from '@/composables/useErpBillEditDelete';

type LineRow = SalesShipmentLine & { _key: string; spc?: string };

const TAX_OPTIONS = [
  { value: '1', label: '不计税' },
  { value: '2', label: '应税内含' },
  { value: '3', label: '应税外加' },
];

const ZHANG_OPTIONS = [
  { value: '1', label: '单张立帐' },
  { value: '2', label: '不立帐' },
  { value: '3', label: '收到发票才立帐' },
];

function today(): string {
  return new Date().toISOString().slice(0, 10);
}

function newLine(key: string): LineRow {
  return {
    _key: key,
    prd_no: '',
    prd_name: '',
    prd_mark: '',
    wh: '',
    qty: 0,
    ut: '',
    up: 0,
    amtn_net: 0,
    tax_rto: 13,
    tax: 0,
    dis_cnt: 0,
    qty1: 0,
    bat_no: '',
    est_dd: '',
    sup_prd_no: '',
    rem: '',
    os_id: 'SO',
    os_no: '',
    ext_fields: {},
  };
}

function recalcLine(ln: LineRow, taxId: string): LineRow {
  const c = calcLineAmounts(ln.qty, ln.up, taxId, ln.tax_rto ?? 13);
  return { ...ln, amtn_net: c.amtn_net, tax: c.tax };
}

const head = reactive<SalesShipmentHead>({
  ps_no: '',
  ps_dd: today(),
  cus_no: '',
  tax_id: '2',
  os_id: 'SO',
  zhang_id: '1',
  dis_cnt: 0,
  ext_fields: {},
});

const lines = ref<LineRow[]>([]);
const list = ref<SalesShipmentHead[]>([]);
const filters = reactive({
  ps_no: '',
  cus_no: '',
  dateFrom: '',
  dateTo: '',
});
/** 字段配置 — 同步 analysis/字段对照/销货单.md */
const headQueryFields = pickQuery(INV_CA.head);
const headListFields = pickList(INV_CA.head);
const lineFormFields = pickForm(INV_CA.line);
const loading = ref(false);
const saving = ref(false);
const custs = ref<Cust[]>([]);
const salms = ref<Salm[]>([]);
const depts = ref<Dept[]>([]);
const products = ref<Product[]>([]);
const whs = ref<Warehouse[]>([]);
const openOrders = ref<OpenSalesOrder[]>([]);
const editing = ref<string | null>(null);

const custPicker = ref(false);
const salPicker = ref(false);
const depPicker = ref(false);
const bilTypePicker = ref(false);
const bilTypeName = ref('');
const sendWhPicker = ref(false);
const soPicker = ref(false);
const prdPicker = ref(false);
const prdLineIdx = ref<number | null>(null);

const custName = computed(
  () => custs.value.find((c) => c.cus_no === head.cus_no)?.name || ''
);
const salName = computed(
  () => salms.value.find((s) => s.sal_no === head.sal_no)?.name || ''
);
const depName = computed(
  () => depts.value.find((d) => d.dep === head.dep)?.name || ''
);
const sendWhName = computed(
  () => whs.value.find((w) => w.wh === head.send_wh)?.name || ''
);

const bilTypeDisplay = computed(() => {
  const code = head.bil_type?.trim() || '';
  if (!code) return '';
  const name = bilTypeName.value.trim();
  return name ? `${code} ${name}` : code;
});

function applyBilSpc(row: BilSpc) {
  head.bil_type = row.spc_no;
  bilTypeName.value = row.name?.trim() || '';
  bilTypePicker.value = false;
}

const totals = computed(() => sumLines(lines.value));

const displayList = computed(() => {
  let rows = list.value;
  const qNo = filters.ps_no.trim().toLowerCase();
  const qCus = filters.cus_no.trim().toLowerCase();
  if (qNo) {
    rows = rows.filter(
      (r) =>
        r.ps_no?.toLowerCase().includes(qNo) ||
        r.os_no?.toLowerCase().includes(qNo)
    );
  }
  if (qCus) {
    rows = rows.filter(
      (r) =>
        r.cus_name?.toLowerCase().includes(qCus) ||
        r.cus_no?.toLowerCase().includes(qCus)
    );
  }
  if (filters.dateFrom) rows = rows.filter((r) => (r.ps_dd || '') >= filters.dateFrom);
  if (filters.dateTo) rows = rows.filter((r) => (r.ps_dd || '') <= filters.dateTo);
  return rows;
});

function resetQuery() {
  filters.ps_no = '';
  filters.cus_no = '';
  filters.dateFrom = '';
  filters.dateTo = '';
}

async function loadMasters() {
  const [c, s, d, w, p] = await Promise.all([
    api.custList({ limit: 500 }),
    api.salmList(),
    api.deptList(),
    api.warehouses(),
    api.productList({ limit: 500 }),
  ]);
  custs.value = c.data;
  salms.value = s.data;
  depts.value = d.data;
  whs.value = w.data;
  products.value = p.data;
}

async function loadList() {
  loading.value = true;
  try {
    const { data } = await api.salesShipmentList({ limit: 200 });
    list.value = data;
  } finally {
    loading.value = false;
  }
}

async function onNew() {
  const { data } = await api.nextSalesShipmentNo();
  Object.assign(head, {
    ps_no: data.ps_no,
    ps_dd: today(),
    cus_no: '',
    cus_name: '',
    dep: '',
    sal_no: '',
    cus_os_no: '',
    bil_type: '',
    cur_id: 'RMB',
    tax_id: '2',
    os_id: 'SO',
    os_no: '',
    zhang_id: '1',
    send_mth: '',
    send_wh: '',
    adr: '',
    pay_mth: '',
    pay_days: undefined,
    pay_dd: '',
    chk_dd: '',
    inv_no: '',
    rp_no: '',
    voh_no: '',
    contract: '',
    rem: '',
    dis_cnt: 0,
    amtn_net: 0,
    tax: 0,
    ext_fields: {},
  });
  lines.value = [];
  editing.value = null;
}

function applyCust(c: Cust) {
  head.cus_no = c.cus_no;
  head.sal_no = c.sal_no || head.sal_no;
  head.cur_id = c.cur_id || 'RMB';
  head.tax_id = c.id1_tax || '2';
  head.adr = c.adr2 || head.adr;
  lines.value = lines.value.map((ln) => recalcLine(ln, head.tax_id || '2'));
}

function addLine() {
  lines.value = [...lines.value, newLine(String(lines.value.length + 1))];
}
const { onAddLines } = useBillLineAddRows(addLine);

function removeLine(idx: number) {
  lines.value = lines.value.filter((_, i) => i !== idx);
}

function openProductPicker(idx: number) {
  prdLineIdx.value = idx;
  prdPicker.value = true;
}

function applyProduct(p: Product) {
  if (prdLineIdx.value == null) return;
  updateLine(prdLineIdx.value, {
    prd_no: p.prd_no,
    prd_name: p.name || '',
    spc: p.spc,
    ut: p.ut,
    wh: p.wh,
    up: p.upr ?? 0,
  });
  prdPicker.value = false;
  prdLineIdx.value = null;
}

function onLineProductFromRow(index: number, p: Record<string, unknown>) {
  updateLine(index, {
    prd_no: String(p.prd_no ?? ''),
    prd_name: String(p.name || ''),
    spc: String(p.spc ?? ''),
    ut: String(p.ut ?? ''),
    wh: String(p.wh ?? ''),
    up: Number(p.upr ?? 0),
  });
}

function onTaxChange() {
  lines.value = lines.value.map((ln) => recalcLine(ln, head.tax_id || '2'));
}

function updateLine(idx: number, patch: Partial<LineRow>) {
  const next = [...lines.value];
  next[idx] = recalcLine({ ...next[idx], ...patch }, head.tax_id || '2');
  lines.value = next;
}

async function openSoTransfer() {
  if (!head.cus_no) {
    ElMessage.warning('请先选择销货客户');
    return;
  }
  const { data } = await api.openSalesOrders(head.cus_no);
  if (!data.length) {
    ElMessage.info('该客户没有未交完的销售订单');
    return;
  }
  openOrders.value = data;
  soPicker.value = true;
}

async function transferFromSo(osNo: string) {
  try {
    const { data } = await api.salesOrderShipLines(osNo);
    const h = data.head;
    head.os_id = 'SO';
    head.os_no = h.os_no;
    head.cus_no = h.cus_no || head.cus_no;
    head.sal_no = h.sal_no || head.sal_no;
    head.cur_id = h.cur_id || head.cur_id;
    head.tax_id = h.tax_id || head.tax_id;
    head.cus_os_no = h.cus_os_no || '';
    head.bil_type = h.bil_type || '';
    bilTypeName.value = '';
    head.dep = h.use_dep || '';
    lines.value = data.lines.map((ln, i) =>
      recalcLine(
        {
          ...newLine(String(i + 1)),
          prd_no: ln.prd_no,
          prd_name: ln.prd_name,
          spc: ln.spc,
          wh: ln.wh,
          qty: ln.qty_open ?? ln.qty,
          ut: ln.ut,
          up: ln.up,
          tax_rto: ln.tax_rto ?? 13,
          est_dd: ln.est_dd,
          sup_prd_no: ln.sup_prd_no,
          rem: ln.rem,
          os_id: 'SO',
          os_no: h.os_no,
          src_itm: ln.itm,
        },
        head.tax_id || '2'
      )
    );
    soPicker.value = false;
    ElMessage.success(`已从销售订单 ${osNo} 带入表身`);
  } catch {
    ElMessage.error('转入失败');
  }
}

async function onSave() {
  if (!head.cus_no) {
    ElMessage.warning('请选择销货客户');
    return;
  }
  if (!lines.value.length) {
    ElMessage.warning('请先转入或录入表身');
    return;
  }
  const validLines = lines.value.filter((ln) => ln.prd_no?.trim());
  if (!validLines.length) {
    ElMessage.warning('表身至少一行有效货品');
    return;
  }
  const payload = buildBillSavePayload(head, validLines, ({ _key, spc, qty_open, ...rest }) => rest);
  saving.value = true;
  try {
    if (editing.value) {
      await api.updateSalesShipment(editing.value, payload);
      ElMessage.success('更新成功');
    } else {
      await api.createSalesShipment(payload);
      ElMessage.success('存盘成功');
      editing.value = head.ps_no;
    }
    await loadList();
  } catch (e: unknown) {
    const err = e as { response?: { data?: { error?: string } } };
    ElMessage.error(err.response?.data?.error || '存盘失败');
  } finally {
    saving.value = false;
  }
}

async function openShipment(psNo: string) {
  const { data } = await api.getSalesShipment(psNo);
  Object.assign(head, data.head);
  editing.value = psNo;
  lines.value = data.lines.map((l, i) =>
    recalcLine({ ...l, _key: String(i + 1), spc: l.spc, ext_fields: l.ext_fields ?? {} }, head.tax_id || '2')
  );
}

async function openAdd() {
  await onNew();
}

async function openEdit(row: SalesShipmentHead) {
  await openShipment(row.ps_no);
}

const {
  deleting,
  editPicker,
  canDelete,
  onToolbarEdit,
  onToolbarDelete,
  onPickEdit,
} = useErpBillEditDelete({
  billLabel: '销货单',
  billNoKey: 'ps_no',
  getBillNo: () => head.ps_no,
  editing,
  list,
  openBill: openShipment,
  resetNew: onNew,
  reloadList: loadList,
  deleteBill: (no) => api.deleteSalesShipment(no).then(() => undefined),
});

onMounted(async () => {
  try {
    await loadMasters();
    await loadList();
  } catch {
    ElMessage.error('加载销货单失败');
  }
});
</script>

<template>
  <ErpBillPage title="销货单" subtitle="顶部查询 · 表头表身页内维护 · 下方浏览历史单据" :loading="loading" :menu-code="INV_CA.menuCode">
    <template #toolbar>
      <ErpBillToolbar @search="loadList" @reset="resetQuery">
        <template #actions>
          <el-button type="primary" @click="openAdd">新增</el-button>
          <el-button type="success" :loading="saving" @click="onSave">存盘</el-button>
          <el-button @click="onToolbarEdit">编辑</el-button>
          <el-button type="danger" :loading="deleting" :disabled="!canDelete" @click="onToolbarDelete">删除</el-button>
          <el-button @click="loadList">刷新</el-button>
        </template>
        <template #query>
          <ErpBillQueryField
            v-for="f in headQueryFields"
            :key="f.dbField"
            :label="f.label"
            :width="f.key === 'ps_dd' ? 280 : undefined"
          >
            <template v-if="f.key === 'ps_dd'">
              <div style="display: flex; gap: 6px; width: 100%">
                <el-date-picker v-model="filters.dateFrom" type="date" value-format="YYYY-MM-DD" placeholder="起" style="flex: 1" />
                <el-date-picker v-model="filters.dateTo" type="date" value-format="YYYY-MM-DD" placeholder="止" style="flex: 1" />
              </div>
            </template>
            <el-input
              v-else-if="f.key === 'ps_no'"
              v-model="filters.ps_no"
              clearable
              placeholder="模糊查询"
              @keyup.enter="loadList"
            />
            <el-input
              v-else-if="f.key === 'cus_no'"
              v-model="filters.cus_no"
              clearable
              placeholder="代号/名称"
              @keyup.enter="loadList"
            />
          </ErpBillQueryField>
        </template>
      </ErpBillToolbar>
    </template>

    <template #header>
      <div class="erp-bill-section-head">
        <span>表头</span>
        <div class="erp-bill-section-actions">
          <el-button size="small" @click="addLine">增行</el-button>
          <el-button size="small" @click="openSoTransfer">从销售订单转入</el-button>
        </div>
      </div>
      <el-form label-width="96px" label-position="right" class="erp-bill-header-form">
          <el-row :gutter="12">
            <el-col :span="6">
              <el-form-item label="日期" required data-field="PS_DD">
                <el-date-picker v-model="head.ps_dd" type="date" value-format="YYYY-MM-DD" style="width: 100%" />
              </el-form-item>
            </el-col>
            <el-col :span="6">
              <el-form-item label="单号" data-field="PS_NO">
                <el-input v-model="head.ps_no" readonly />
              </el-form-item>
            </el-col>
            <el-col :span="6">
              <el-form-item label="转入单号" data-field="OS_NO">
                <el-input v-model="head.os_no" readonly placeholder="从销售订单转入" />
              </el-form-item>
            </el-col>
            <el-col :span="6">
              <el-form-item label="客户订单号" data-field="CUS_OS_NO">
                <el-input v-model="head.cus_os_no" />
              </el-form-item>
            </el-col>
          </el-row>
          <el-row :gutter="12">
            <el-col :span="6">
              <el-form-item label="客户代号" required data-field="CUS_NO">
                <LookupField :model-value="head.cus_no" :display="custName" @open="custPicker = true" />
              </el-form-item>
            </el-col>
            <el-col :span="6">
              <el-form-item label="业务员代号" data-field="SAL_NO">
                <LookupField :model-value="head.sal_no" :display="salName" @open="salPicker = true" />
              </el-form-item>
            </el-col>
            <el-col :span="6">
              <el-form-item label="单据类别" data-field="BIL_TYPE">
                <LookupField
                  :model-value="head.bil_type"
                  :display="bilTypeDisplay"
                  placeholder="选择单据类别"
                  @open="bilTypePicker = true"
                />
              </el-form-item>
            </el-col>
            <el-col :span="6">
              <el-form-item label="部门代号" data-field="DEP">
                <LookupField :model-value="head.dep" :display="depName" @open="depPicker = true" />
              </el-form-item>
            </el-col>
          </el-row>
          <el-row :gutter="12">
            <el-col :span="6">
              <el-form-item label="币别" data-field="CUR_ID">
                <LookupPicker v-model="head.cur_id" preset="currency" placeholder="选择币别" />
              </el-form-item>
            </el-col>
            <el-col :span="6">
              <el-form-item label="扣税类别" data-field="TAX_ID">
                <el-select v-model="head.tax_id" style="width: 100%" @change="onTaxChange">
                  <el-option v-for="o in TAX_OPTIONS" :key="o.value" :label="o.label" :value="o.value" />
                </el-select>
              </el-form-item>
            </el-col>
            <el-col :span="6">
              <el-form-item label="折扣" data-field="DIS_CNT">
                <el-input-number v-model="head.dis_cnt" :min="0" :max="100" style="width: 100%" />
              </el-form-item>
            </el-col>
            <el-col :span="6">
              <el-form-item label="立帐方式" data-field="ZHANG_ID">
                <el-select v-model="head.zhang_id" style="width: 100%">
                  <el-option v-for="o in ZHANG_OPTIONS" :key="o.value" :label="o.label" :value="o.value" />
                </el-select>
              </el-form-item>
            </el-col>
            <el-col :span="6">
              <el-form-item label="交货方式" data-field="SEND_MTH">
                <el-input v-model="head.send_mth" />
              </el-form-item>
            </el-col>
            <el-col :span="6">
              <el-form-item label="交货仓" data-field="SEND_WH">
                <LookupField :model-value="head.send_wh" :display="sendWhName" @open="sendWhPicker = true" />
              </el-form-item>
            </el-col>
            <el-col :span="6">
              <el-form-item label="交易方式" data-field="PAY_MTH">
                <el-input v-model="head.pay_mth" />
              </el-form-item>
            </el-col>
          </el-row>
          <el-row :gutter="12">
            <el-col :span="6">
              <el-form-item label="付款天数" data-field="PAY_DAYS">
                <el-input-number v-model="head.pay_days" :min="0" style="width: 100%" />
              </el-form-item>
            </el-col>
            <el-col :span="6">
              <el-form-item label="付款日期" data-field="PAY_DD">
                <el-date-picker v-model="head.pay_dd" type="date" value-format="YYYY-MM-DD" style="width: 100%" />
              </el-form-item>
            </el-col>
            <el-col :span="6">
              <el-form-item label="票据日期" data-field="CHK_DD">
                <el-date-picker v-model="head.chk_dd" type="date" value-format="YYYY-MM-DD" style="width: 100%" />
              </el-form-item>
            </el-col>
            <el-col :span="6">
              <el-form-item label="合同号" data-field="CONTRACT">
                <el-input v-model="head.contract" />
              </el-form-item>
            </el-col>
          </el-row>
          <el-row :gutter="12">
            <el-col :span="6">
              <el-form-item label="发票号码" data-field="INV_NO">
                <el-input v-model="head.inv_no" readonly />
              </el-form-item>
            </el-col>
            <el-col :span="6">
              <el-form-item label="收付款单号" data-field="RP_NO">
                <el-input v-model="head.rp_no" readonly />
              </el-form-item>
            </el-col>
            <el-col :span="6">
              <el-form-item label="凭证号码" data-field="VOH_NO">
                <el-input v-model="head.voh_no" readonly />
              </el-form-item>
            </el-col>
          </el-row>
          <el-form-item label="送货地址" data-field="ADR">
            <el-input v-model="head.adr" type="textarea" :rows="2" />
          </el-form-item>
          <el-form-item label="备注" data-field="REM">
            <el-input v-model="head.rem" type="textarea" :rows="2" />
          </el-form-item>
          <ErpBillAuditMeta :meta="head" />
          <ErpBillHeadExtFields v-model="head.ext_fields" :menu-code="INV_CA.menuCode" />
        </el-form>
    </template>

    <template #lines>
      <div class="erp-bill-section-head">
        <span>表身明细</span>
      </div>
      <ErpBillLineTable
        :fields="lineFormFields"
        :lines="lines"
        :whs="whs"
        :menu-code="INV_CA.menuCode"
        :lookup-products="(products as unknown as Record<string, unknown>[])"
        :lookup-resolve-by-code="resolveLineProductByCode"
        @add-lines="onAddLines"
        @update-line="updateLine"
        @open-product-picker="openProductPicker"
        @select-product="onLineProductFromRow"
      >
        <template #actions="{ index }">
          <el-button link type="danger" size="small" @click="removeLine(index)">删</el-button>
        </template>
      </ErpBillLineTable>
    </template>

    <template #totals>
      <div class="erp-bill-totals-row">
        <span>未税本币：<strong>{{ totals.amtn_net }}</strong></span>
        <span>税额：<strong>{{ totals.tax }}</strong></span>
        <span>合计：<strong>{{ totals.total }}</strong></span>
      </div>
    </template>

    <template #listTitle>历史单据</template>
    <template #list>
      <el-table
        :data="displayList"
        border
        stripe
        highlight-current-row
        max-height="240"
        empty-text="暂无单据，可调整筛选条件或点击「新增」"
        @row-dblclick="openEdit"
      >
        <el-table-column
          v-for="f in headListFields"
          :key="f.dbField"
          :prop="f.key"
          :label="f.label"
          :width="f.width"
          :min-width="f.minWidth"
          show-overflow-tooltip
          align="center"
        >
          <template #header>
            <span :data-field="f.dbField" :title="f.dbField">{{ f.label }}</span>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="100" fixed="right" align="center">
          <template #default="{ row }">
            <el-button link type="primary" @click="openEdit(row)">编辑</el-button>
          </template>
        </el-table-column>
      </el-table>
    </template>

    <template #footer>
      <div v-if="displayList.length" class="erp-table-footer">
        <span class="erp-table-total">共 <strong>{{ displayList.length }}</strong> 条</span>
      </div>
    </template>
  </ErpBillPage>

  <BilSpcSalesLookupDialog v-model="bilTypePicker" @select="applyBilSpc" />

  <LookupDialog
    v-model="custPicker"
    v-bind="getLookupDialogProps('cust')"
    :data="custs"
    @select="applyCust"
  />

  <LookupDialog
    v-model="salPicker"
    v-bind="getLookupDialogProps('salm')"
    :data="salms"
    @select="(r: Salm) => { head.sal_no = r.sal_no; }"
  />

  <LookupDialog
    v-model="depPicker"
    v-bind="getLookupDialogProps('dept')"
    :data="depts"
    @select="(r: Dept) => { head.dep = r.dep; }"
  />

  <LookupDialog
    v-model="sendWhPicker"
    v-bind="getLookupDialogProps('warehouse', { title: '选择交货仓' })"
    :data="whs"
    @select="(r: Warehouse) => { head.send_wh = r.wh; }"
  />

  <LookupDialog
    v-model="prdPicker"
    v-bind="getLookupDialogProps('product')"
    :data="products"
    @select="applyProduct"
  />

  <LookupDialog
    v-model="soPicker"
    v-bind="getInlineLookupDialogProps({
      title: '选择销售订单（未交完）',
      rowKey: 'os_no',
      searchKeys: ['os_no', 'cus_os_no'],
      columns: [
        { prop: 'os_no', label: 'OS_NO', width: 120 },
        { prop: 'os_dd', label: 'OS_DD', width: 100 },
        { prop: 'cus_os_no', label: 'CUS_OS_NO', minWidth: 120 },
      ],
    })"
    :data="openOrders"
    @select="(r: OpenSalesOrder) => transferFromSo(r.os_no)"
  />

  <LookupDialog
    v-model="editPicker"
    v-bind="getInlineLookupDialogProps({
      title: '选择销货单',
      rowKey: 'ps_no',
      searchKeys: ['ps_no', 'cus_no', 'cus_name', 'os_no'],
      columns: [
        { prop: 'ps_no', label: 'PS_NO', width: 120 },
        { prop: 'ps_dd', label: 'PS_DD', width: 100 },
        { prop: 'cus_no', label: 'CUS_NO', width: 90 },
        { prop: 'cus_name', label: 'CUS_NAME', minWidth: 120 },
      ],
    })"
    :data="list"
    @select="onPickEdit"
  />
</template>

// erp-new/client/src/pages/SalesShipmentPage.tsx
import { useEffect, useMemo, useState } from 'react';
import {
  Button,
  Card,
  Col,
  DatePicker,
  Form,
  Input,
  InputNumber,
  Row,
  Select,
  Space,
  Table,
  message,
} from 'antd';
import dayjs from 'dayjs';
import LookupField from '../components/LookupField';
import LookupModal from '../components/LookupModal';
import {
  api,
  type Cust,
  type OpenSalesOrder,
  type SalesShipmentHead,
  type SalesShipmentLine,
  type Salm,
  type Warehouse,
} from '../api';

type LineRow = SalesShipmentLine & { key: string };

const TAX_OPTIONS = [
  { value: '1', label: '不计税' },
  { value: '2', label: '应税内含' },
  { value: '3', label: '应税外加' },
];

function newLine(key: string): LineRow {
  return {
    key,
    prd_no: '',
    prd_name: '',
    wh: '',
    qty: 0,
    ut: '',
    up: 0,
    amtn_net: 0,
    tax_rto: 13,
    tax: 0,
    est_dd: '',
    sup_prd_no: '',
    rem: '',
    os_id: 'SO',
    os_no: '',
  };
}

function recalcLine(ln: LineRow, taxId: string): LineRow {
  const qty = Number(ln.qty) || 0;
  const up = Number(ln.up) || 0;
  const rto = Number(ln.tax_rto) || 0;
  const gross = Math.round(qty * up * 100) / 100;
  let amtn_net = gross;
  let tax = 0;
  if (taxId === '2') {
    tax = Math.round((gross * rto) / (100 + rto) * 100) / 100;
    amtn_net = Math.round((gross - tax) * 100) / 100;
  } else if (taxId === '3') {
    amtn_net = gross;
    tax = Math.round((amtn_net * rto) / 100 * 100) / 100;
  }
  return { ...ln, amtn_net, tax };
}

export default function SalesShipmentPage() {
  const [form] = Form.useForm<SalesShipmentHead>();
  const [lines, setLines] = useState<LineRow[]>([]);
  const [shipments, setShipments] = useState<SalesShipmentHead[]>([]);
  const [custs, setCusts] = useState<Cust[]>([]);
  const [whs, setWhs] = useState<Warehouse[]>([]);
  const [salms, setSalms] = useState<Salm[]>([]);
  const [openOrders, setOpenOrders] = useState<OpenSalesOrder[]>([]);
  const [editing, setEditing] = useState<string | null>(null);
  const [custPicker, setCustPicker] = useState(false);
  const [salPicker, setSalPicker] = useState(false);
  const [soPicker, setSoPicker] = useState(false);

  const taxId = Form.useWatch('tax_id', form) || '2';
  const cusNo = Form.useWatch('cus_no', form);

  const totals = useMemo(() => {
    let amtn = 0;
    let tax = 0;
    for (const ln of lines) {
      amtn += Number(ln.amtn_net) || 0;
      tax += Number(ln.tax) || 0;
    }
    return {
      amtn_net: Math.round(amtn * 100) / 100,
      tax: Math.round(tax * 100) / 100,
      total: Math.round((amtn + tax) * 100) / 100,
    };
  }, [lines]);

  const load = async () => {
    const [sh, c, w, s] = await Promise.all([
      api.salesShipmentList({ limit: 100 }),
      api.custList({ limit: 500 }),
      api.warehouses(),
      api.salmList(),
    ]);
    setShipments(sh.data);
    setCusts(c.data);
    setWhs(w.data);
    setSalms(s.data);
  };

  useEffect(() => {
    load().catch(() => message.error('加载销货单失败'));
  }, []);

  const onNew = async () => {
    form.resetFields();
    const { data } = await api.nextSalesShipmentNo();
    form.setFieldsValue({
      ps_no: data.ps_no,
      ps_dd: dayjs(),
      tax_id: '2',
      dis_cnt: 0,
      os_id: 'SO',
    } as unknown as SalesShipmentHead);
    setLines([]);
    setEditing(null);
  };

  useEffect(() => {
    onNew().catch(() => {});
  }, []);

  const applyCust = (c: Cust) => {
    form.setFieldsValue({
      cus_no: c.cus_no,
      sal_no: c.sal_no,
      cur_id: c.cur_id || 'RMB',
      tax_id: c.id1_tax || '2',
    });
  };

  const custName = (no?: string) => custs.find((c) => c.cus_no === no)?.name || '';
  const salName = (no?: string) => salms.find((s) => s.sal_no === no)?.name || '';

  const openSoTransfer = async () => {
    const cus = form.getFieldValue('cus_no');
    if (!cus) return message.warning('请先选择销货客户');
    const { data } = await api.openSalesOrders(String(cus));
    if (!data.length) return message.info('该客户没有未交完的受订单');
    setOpenOrders(data);
    setSoPicker(true);
  };

  const transferFromSo = async (osNo: string) => {
    try {
      const { data } = await api.salesOrderShipLines(osNo);
      const head = data.head;
      form.setFieldsValue({
        os_id: 'SO',
        os_no: head.os_no,
        cus_no: head.cus_no,
        sal_no: head.sal_no,
        cur_id: head.cur_id,
        tax_id: head.tax_id,
        cus_os_no: head.cus_os_no,
        bil_type: head.bil_type,
        dep: head.use_dep,
      });
      setLines(
        data.lines.map((ln, i) =>
          recalcLine(
            {
              ...newLine(String(i + 1)),
              key: String(i + 1),
              prd_no: ln.prd_no,
              prd_name: ln.prd_name,
              wh: ln.wh,
              spc: ln.spc,
              qty: ln.qty_open ?? ln.qty,
              ut: ln.ut,
              up: ln.up,
              tax_rto: ln.tax_rto,
              est_dd: ln.est_dd,
              sup_prd_no: ln.sup_prd_no,
              rem: ln.rem,
              os_id: 'SO',
              os_no: head.os_no,
              src_itm: ln.itm,
            },
            String(head.tax_id || '2')
          )
        )
      );
      setSoPicker(false);
      message.success(`已从受订单 ${osNo} 带入表身`);
    } catch {
      message.error('转入失败');
    }
  };

  const onSave = async () => {
    const head = await form.validateFields();
    if (!lines.length) return message.warning('请先转入或录入表身');
    const payload = {
      head: {
        ...head,
        ps_dd: head.ps_dd ? (head.ps_dd as unknown as dayjs.Dayjs).format('YYYY-MM-DD') : undefined,
      },
      lines: lines.map(({ key: _k, spc: _s, qty_open: _q, ...rest }) => rest),
    };
    try {
      if (editing) {
        await api.updateSalesShipment(editing, payload);
        message.success('更新成功');
      } else {
        await api.createSalesShipment(payload);
        message.success('存盘成功');
        onNew();
      }
      load();
    } catch (e: unknown) {
      const err = e as { response?: { data?: { error?: string } } };
      message.error(err.response?.data?.error || '存盘失败');
    }
  };

  const openShipment = async (psNo: string) => {
    const { data } = await api.getSalesShipment(psNo);
    setEditing(psNo);
    form.setFieldsValue({
      ...data.head,
      ps_dd: data.head.ps_dd ? dayjs(data.head.ps_dd) : undefined,
    } as unknown as SalesShipmentHead);
    setLines(data.lines.map((l, i) => recalcLine({ ...l, key: String(i + 1) }, String(data.head.tax_id || '2'))));
  };

  const updateLine = (idx: number, patch: Partial<LineRow>) => {
    setLines((prev) => {
      const next = [...prev];
      next[idx] = recalcLine({ ...next[idx], ...patch }, taxId);
      return next;
    });
  };

  return (
    <div style={{ padding: 16 }}>
      <Row gutter={16}>
        <Col span={16}>
          <Card
            title="销货单"
            extra={
              <Space>
                <Button onClick={onNew}>新增</Button>
                <Button onClick={openSoTransfer}>从受订单转入</Button>
                <Button type="primary" onClick={onSave}>
                  存盘
                </Button>
              </Space>
            }
          >
            <Form form={form} layout="vertical">
              <Row gutter={8}>
                <Col span={6}>
                  <Form.Item name="ps_no" label="销货单号">
                    <Input readOnly />
                  </Form.Item>
                </Col>
                <Col span={6}>
                  <Form.Item name="ps_dd" label="销货日期" rules={[{ required: true }]}>
                    <DatePicker style={{ width: '100%' }} />
                  </Form.Item>
                </Col>
                <Col span={6}>
                  <Form.Item name="os_no" label="转入单号（受订单）">
                    <Input readOnly placeholder="从受订单转入" />
                  </Form.Item>
                </Col>
                <Col span={6}>
                  <Form.Item name="cus_os_no" label="客户单号">
                    <Input />
                  </Form.Item>
                </Col>
              </Row>
              <Row gutter={8}>
                <Col span={12}>
                  <Form.Item name="cus_no" label="销货客户" rules={[{ required: true }]}>
                    <LookupField display={custName(cusNo)} onOpen={() => setCustPicker(true)} />
                  </Form.Item>
                </Col>
                <Col span={6}>
                  <Form.Item name="sal_no" label="业务人员">
                    <LookupField display={salName(form.getFieldValue('sal_no'))} onOpen={() => setSalPicker(true)} />
                  </Form.Item>
                </Col>
                <Col span={6}>
                  <Form.Item name="bil_type" label="单据类别">
                    <Input />
                  </Form.Item>
                </Col>
              </Row>
              <Row gutter={8}>
                <Col span={6}>
                  <Form.Item name="cur_id" label="币别">
                    <Input placeholder="RMB" />
                  </Form.Item>
                </Col>
                <Col span={6}>
                  <Form.Item name="tax_id" label="扣税类别">
                    <Select
                      options={TAX_OPTIONS}
                      onChange={() => setLines((prev) => prev.map((l) => recalcLine(l, form.getFieldValue('tax_id'))))}
                    />
                  </Form.Item>
                </Col>
                <Col span={6}>
                  <Form.Item name="dep" label="部门">
                    <Input />
                  </Form.Item>
                </Col>
                <Col span={6}>
                  <Form.Item name="dis_cnt" label="折扣%">
                    <InputNumber min={0} max={100} style={{ width: '100%' }} />
                  </Form.Item>
                </Col>
              </Row>
              <Form.Item name="rem" label="备注">
                <Input />
              </Form.Item>
              <Form.Item name="os_id" hidden>
                <Input />
              </Form.Item>
            </Form>

            <Table
              size="small"
              rowKey="key"
              dataSource={lines}
              pagination={false}
              scroll={{ x: 1100 }}
              columns={[
                { title: '序号', width: 50, render: (_v, _r, i) => i + 1 },
                { title: '品号', dataIndex: 'prd_no', width: 110 },
                { title: '品名', dataIndex: 'prd_name', width: 120, ellipsis: true },
                { title: '规格', dataIndex: 'spc', width: 100, ellipsis: true },
                {
                  title: '仓库',
                  dataIndex: 'wh',
                  width: 90,
                  render: (v, _r, i) => (
                    <Select
                      size="small"
                      style={{ width: '100%' }}
                      value={v || undefined}
                      allowClear
                      showSearch
                      optionFilterProp="label"
                      options={whs.map((w) => ({ value: w.wh, label: w.wh }))}
                      onChange={(val) => updateLine(i, { wh: val })}
                    />
                  ),
                },
                {
                  title: '数量',
                  dataIndex: 'qty',
                  width: 90,
                  render: (v, _r, i) => (
                    <InputNumber size="small" value={v} min={0} onChange={(val) => updateLine(i, { qty: val ?? 0 })} />
                  ),
                },
                { title: '单位', dataIndex: 'ut', width: 60 },
                {
                  title: '单价',
                  dataIndex: 'up',
                  width: 90,
                  render: (v, _r, i) => (
                    <InputNumber size="small" value={v} min={0} step={0.01} onChange={(val) => updateLine(i, { up: val ?? 0 })} />
                  ),
                },
                { title: '未税', dataIndex: 'amtn_net', width: 80 },
                { title: '税额', dataIndex: 'tax', width: 70 },
                { title: '对方货号', dataIndex: 'sup_prd_no', width: 90, ellipsis: true },
                { title: '来源单号', dataIndex: 'os_no', width: 100 },
              ]}
            />

            <Row gutter={16} style={{ marginTop: 12 }}>
              <Col span={8}>未税本币：{totals.amtn_net}</Col>
              <Col span={8}>税额：{totals.tax}</Col>
              <Col span={8}>合计：{totals.total}</Col>
            </Row>
          </Card>
        </Col>
        <Col span={8}>
          <Card title="销货单列表">
            <Table
              rowKey="ps_no"
              size="small"
              dataSource={shipments}
              pagination={{ pageSize: 10 }}
              onRow={(r) => ({ onDoubleClick: () => openShipment(r.ps_no) })}
              columns={[
                { title: '单号', dataIndex: 'ps_no', width: 110 },
                { title: '日期', dataIndex: 'ps_dd', width: 90 },
                { title: '客户', dataIndex: 'cus_name', ellipsis: true },
              ]}
            />
          </Card>
        </Col>
      </Row>

      <LookupModal
        open={custPicker}
        title="选择客户"
        rowKey="cus_no"
        dataSource={custs}
        searchKeys={['cus_no', 'name', 'snm']}
        onCancel={() => setCustPicker(false)}
        onSelect={(r) => {
          applyCust(r);
          setCustPicker(false);
        }}
        columns={[
          { title: '代号', dataIndex: 'cus_no', width: 90 },
          { title: '全称', dataIndex: 'name', ellipsis: true },
        ]}
      />

      <LookupModal
        open={salPicker}
        title="选择业务员"
        rowKey="sal_no"
        dataSource={salms}
        searchKeys={['sal_no', 'name']}
        onCancel={() => setSalPicker(false)}
        onSelect={(r) => {
          form.setFieldValue('sal_no', r.sal_no);
          setSalPicker(false);
        }}
        columns={[
          { title: '代号', dataIndex: 'sal_no', width: 90 },
          { title: '姓名', dataIndex: 'name' },
        ]}
      />

      <LookupModal
        open={soPicker}
        title="选择受订单（未交完）"
        rowKey="os_no"
        dataSource={openOrders}
        searchKeys={['os_no', 'cus_os_no']}
        onCancel={() => setSoPicker(false)}
        onSelect={(r) => transferFromSo(r.os_no)}
        columns={[
          { title: '受订单号', dataIndex: 'os_no', width: 120 },
          { title: '日期', dataIndex: 'os_dd', width: 100 },
          { title: '客户单号', dataIndex: 'cus_os_no', ellipsis: true },
        ]}
      />
    </div>
  );
}
